version: "3.9"

services:
  postgres:
    image: postgres:14.5-alpine3.16
    container_name: postgres
    env_file:
      - .env
    networks:
      - db-network
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  db-migrations:
    image: migrate/migrate
    container_name: db-migrations
    env_file:
      - .env
    networks:
      - db-network
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres
    command: -path=migrations/ -database postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$DB?sslmode=disable up
  app:
    build: .
    image: app
    container_name: app
    env_file:
      - .env
    networks:
      - db-network
    environment:
      PG_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$DB?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pg-data:
networks:
  db-network:
