app:
  name: 'shuryak-blog-auth-service'
  version: '1.0.0'

grpc:
  port: '50052'

logger:
  log_level: 'debug'

postgres:
  pool_max: 2

certs:
  private_key_pem_path: "/etc/ssl/certs/ed25519key.pem"
  public_key_pem_path: "/etc/ssl/certs/ed25519key.pem.pub"
