app:
  name: 'shuryak-blog-articles-service'
  version: '1.0.0'

grpc:
  port: '50051'

http:
  port: '8081'

logger:
  log_level: 'debug'

postgres:
  pool_max: 2

certs:
  public_key_pem_path: "/etc/ssl/certs/ed25519key.pem.pub"
