---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-postgres-volume
  labels:
    type: local
    app: user-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/user-postgresql"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-postgres-volume-claim
  labels:
    app: user-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-postgres
  template:
    metadata:
      labels:
        app: user-postgres
    spec:
      containers:
        - name: user-postgres
          image: postgres:15.2-alpine3.17
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: user-env
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: user-postgres-data
      volumes:
        - name: user-postgres-data
          persistentVolumeClaim:
            claimName: user-postgres-volume-claim

---

apiVersion: v1
kind: Service
metadata:
  name: user-postgres
  labels:
    app: user-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30020
  selector:
    app: user-postgres
