---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:15.2-alpine3.17
          command: [ 'sh', '-c',
            'until pg_isready -h user-postgres -p 5432; 
                do echo waiting for database; sleep 2; done;' ]
      containers:
        - name: user
          securityContext:
            allowPrivilegeEscalation: false
          image: user-server:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: user-env
          ports:
            - containerPort: 50051
          readinessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 10
            timeoutSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
spec:
  type: NodePort
  ports:
    - port: 50051
      targetPort: 50051
      nodePort: 30030
  selector:
    app: user
