// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/articles/create": {
            "post": {
                "description": "Creates an article",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Creates an article",
                "parameters": [
                    {
                        "description": "article to create",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.createRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.getManyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.response"
                        }
                    }
                }
            }
        },
        "/articles/delete": {
            "delete": {
                "description": "Deletes article by ID",
                "produces": [
                    "application/json"
                ],
                "summary": "Deletes article by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID to delete",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.articleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.response"
                        }
                    }
                }
            }
        },
        "/articles/getById": {
            "get": {
                "description": "Gets article by ID",
                "produces": [
                    "application/json"
                ],
                "summary": "Gets article by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID to get",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.articleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.response"
                        }
                    }
                }
            }
        },
        "/articles/getMany": {
            "get": {
                "description": "Gets collection of articles",
                "produces": [
                    "application/json"
                ],
                "summary": "Gets collection of articles",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "offset to get",
                        "name": "offset",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "count to get",
                        "name": "count",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.getManyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.response"
                        }
                    }
                }
            }
        },
        "/articles/update": {
            "put": {
                "description": "Updates article by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Updates article by ID",
                "parameters": [
                    {
                        "description": "article to update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.updateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.articleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "v1.articleResponse": {
            "type": "object",
            "properties": {
                "author_id": {
                    "type": "integer",
                    "example": 42
                },
                "content": {
                    "type": "object",
                    "additionalProperties": true
                },
                "created_at": {
                    "type": "string",
                    "example": "2022-10-07T14:26:06.510465Z"
                },
                "custom_id": {
                    "type": "string",
                    "example": "article-url"
                },
                "id": {
                    "type": "integer",
                    "example": 1000
                },
                "thumbnail": {
                    "type": "string",
                    "example": "https://smth.com/thumbnail.png"
                },
                "title": {
                    "type": "string",
                    "example": "How to ..."
                }
            }
        },
        "v1.createRequest": {
            "type": "object",
            "required": [
                "author_id",
                "content",
                "custom_id",
                "thumbnail",
                "title"
            ],
            "properties": {
                "author_id": {
                    "type": "integer",
                    "example": 42
                },
                "content": {
                    "type": "object",
                    "additionalProperties": true
                },
                "custom_id": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3,
                    "example": "article-url"
                },
                "thumbnail": {
                    "type": "string",
                    "example": "https://smth.com/thumbnail.png"
                },
                "title": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 5,
                    "example": "How to ..."
                }
            }
        },
        "v1.getManyResponse": {
            "type": "object",
            "properties": {
                "articles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.articleResponse"
                    }
                }
            }
        },
        "v1.response": {
            "type": "object",
            "properties": {
                "error": {}
            }
        },
        "v1.updateRequest": {
            "type": "object",
            "required": [
                "author_id",
                "content",
                "custom_id",
                "id",
                "thumbnail",
                "title"
            ],
            "properties": {
                "author_id": {
                    "type": "integer",
                    "example": 42
                },
                "content": {
                    "type": "object",
                    "additionalProperties": true
                },
                "custom_id": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3,
                    "example": "article-url"
                },
                "id": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 1000
                },
                "thumbnail": {
                    "type": "string",
                    "example": "https://smth.com/thumbnail.png"
                },
                "title": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 5,
                    "example": "How to ..."
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Articles API",
	Description:      "Service for managing articles",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
