service:
  name: 'articles'
  version: '1.0.0'

gateways:
  user_service_name: 'user'

logger:
  level: 'debug'

postgres:
  pool_max: 2

jaeger:
  url: http://jaeger-collector.default.svc.cluster.local:14268/api/traces
